title: OpenCV中文文档
description: 中文版OpenCV文档 OpenCV Documentation for Chinese https://memorycancel.github.io/cnopencvdocs/
theme: just-the-docs

url: https://memorycancel.github.io/cnopencvdocs/

aux_links:
  文档源码: https://github.com/memorycancel/cnopencvdocs
